Repository EPFL-LAP/dynamatic, pull requests merged in 2024-09, with the labels that each got.

#145 [TimingModels] fix timing model library and retrieve logic
  data/components.json
  lib/Support/TimingModels.cpp
Labels: bug, critical

#146 [RTL] Fix in `join_handshake`
  data/vhdl/handshake/join.vhd
Labels: bug, invalid

#85 [Sharing][hdl] Resource sharing support in VHDL backend
  data/rtl-config-vhdl.json
  data/vhdl/support/sharing_support.vhd
  experimental/lib/Transforms/ResourceSharing/Crush.cpp
  experimental/tools/CMakeLists.txt
  experimental/tools/sharing-wrapper-generator/CMakeLists.txt
  experimental/tools/sharing-wrapper-generator/sharing-wrapper-generator.cpp
  include/dynamatic/Dialect/Handshake/HandshakeOps.td
  integration-test/mvt_float/mvt_float.c
  integration-test/mvt_float/mvt_float.h
  lib/Conversion/HandshakeToHW/HandshakeToHW.cpp
  lib/Dialect/Handshake/HandshakeInterfaces.cpp
  lib/Support/TimingModels.cpp
  tools/dynamatic/dynamatic.cpp
  tools/dynamatic/scripts/compile.sh
Labels: major, feature
